### ISSUE TITLE
network not designed for docker

### ISSUE THREAD

**Issue by boistordu** [syncthing/docker#6]
Hi,

We don't get the good ip address in the description of the device which would be a docker container.
I would get : `172.17.0.1:50918`  in place of `192.168.5.100:50101` and sometimes i can't get the up-to-date status because of that if I fix the ip. It is okey from outside a LAN but not inside.

**Comment by boistordu** [comment]
and also only in docker i would get another port and not the one I configured for in the description for the listen address...

**Comment by rubenbe** [comment]
Hi

This is the design of docker (or a limitiation in the case of syncthing).

If you want to have syncthing show the IP of I suggest to use the "--network host" docker option.
This makes the docker container use the network stack of your host machine (instead of its own private one)

You can try the difference:
`docker run  alpine ip addr`
`docker run --network host alpine ip addr`

**Comment by rubenbe** [comment]
Updated readme file to contain the host networking example:
https://github.com/syncthing/docker/blob/cfb8242314e3922b61001044ea3239398744bc42/README.md

**Comment by calmh** [comment]
I think this covers it.
